repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: local
    hooks:
      - id: terraform-fmt
        name: Terraform format
        entry: terraform fmt -check
        language: system
        files: \.tf$
      - id: terraform-init
        name: Terraform initialize
        entry: terraform init -backend=false -input=false -lockfile=readonly
        language: system
        pass_filenames: false
        always_run: true
      - id: terraform-validate
        name: Terraform validate
        entry: terraform validate -no-color
        language: system
        pass_filenames: false
        always_run: true
